name: CI Tests

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:

jobs:
  initial_checks:
    # Mandatory checks before CI tests
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: false
      envs: |
        # Code style
        - linux: codestyle

  tests:
    needs: initial_checks
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: codecov
      display: true
      # Linux PyQt 5.15 and 6.x installations require apt-getting xcb and EGL deps
      # and headless X11 display; as of Python 3.11 Scipy and h5py also need their own deps.
      libraries: |
        apt:
          - '^libxcb.*-dev'
          - libxkbcommon-x11-dev
          - libegl1
          - libopenblas-dev
          - libhdf5-dev

      envs: |
        # Standard tests
        # Linux builds - test on all supported PyQt5/6 and PySide2/6 versions
        - linux: py311-test-pyqt66
        - linux: py313-test-pyqt67
        - linux: py312-test-pyqt68
        - linux: py313-test-pyqt69
        - linux: py314-test-pyqt610
        - linux: py312-test-pyqt611
        - linux: py311-test-pyqt514

        # Documentation build
        - linux: py311-docs-pyqt66
          coverage: false
        - macos: py314-docs-pyqt611
          coverage: false
          libraries:
            brew:
              - enchant

        # Test a few configurations on macOS 15 (Arm)
        - macos: py310-test-pyqt515
        - macos: py311-test-pyqt66
        - macos: py313-test-pyqt69
        - macos: py314-test-pyqt611

        # Test some configurations on Windows
        - windows: py312-test-pyqt67
        - windows: py313-test-pyqt68
        - windows: py314-test-pyqt610

        # Test against latest developer versions of some packages
        - linux: py312-test-pyqt515-dev
        - linux: py311-test-pyqt67-dev
        - linux: py314-test-pyqt68-dev
        - linux: py314-test-pyqt611-dev

  allowed_failures:
    needs: initial_checks
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: codecov
      display: true
      libraries: |
        apt:
          - '^libxcb.*-dev'
          - libxkbcommon-x11-dev
          - libegl1
          - libopenblas-dev
          - libhdf5-dev
        brew:
          - enchant
          - hdf5
      envs: |
        # Python 3.11.0 failing on Windows in test_image.py on
        # > assert df.find_factory(fname) is df.img_data
        - linux: py312-test-pyside66-skipexitcode
        - linux: py313-test-pyside69
        - linux: py314-test-pyside611
        - macos: py312-test-pyside68
        - macos: py314-test-pyside610
        - macos: py313-test-pyqt515
        - windows: py312-test-pyside67
        - windows: py313-test-pyside611
        - windows: py311-test-pyqt515

        # Windows docs build
        - windows: py311-docs-pyqt515
          coverage: false

        # Failure in test_close_tab
        - windows: py311-test-pyqt515

  publish:
    needs: tests
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    secrets:
      pypi_token: ${{ secrets.pypi_token }}
